In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [ ]:
iris = load_iris()
print(type(iris))
print('Data :', iris.data.shape)
print('Label :', iris.target.shape)
print('feature name :', iris.feature_names)
print(' target name', iris.target_names)
print('iris dataset keys\n', iris.keys())

<class 'sklearn.utils.Bunch'>
Data : (150, 4)
Label : (150,)
feature name : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
 target name ['setosa' 'versicolor' 'virginica']
iris dataset keys
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
x = iris.data
y = iris.target

In [ ]:
encoder = OneHotEncoder(sparse=False)
y = y.reshape(-1, 1)
encoded_y = encoder.fit_transform(y)
print(encoded_y.shape)
print(encoded_y[50:55])
print(y[50:55])

(150, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[1]
 [1]
 [1]
 [1]
 [1]]


In [ ]:
def build_DNN():
    model = Sequential()
    model.add(Dense(256, input_dim=4, activation='relu'))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(512, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    opt = Adam(lr=0.01)
    model.compile(opt, loss='categorical_crossentropy',
              metrics=['accuracy'])
    return model

In [ ]:
train_scores = []
test_scores = []
for i in range(1, 10):
    X_train, X_test, Y_train, Y_test = train_test_split(
    x, encoded_y, test_size=0.2, random_state=i)
    model = build_DNN()
    fit_hist = model.fit(X_train, Y_train, batch_size=5, 
                     epochs=10, verbose=0)
    train_scores.append(fit_hist.history['accuracy'][-1])
    test_scores.append(model.evaluate(X_test, Y_test, verbose=0)[1])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
print(train_scores)

[0.9333333373069763, 0.8916666507720947, 0.8999999761581421, 0.9750000238418579, 0.8833333253860474, 0.9166666865348816, 0.8999999761581421, 0.875, 0.875]


In [ ]:
print(test_scores)

[1.0, 1.0, 0.9666666388511658, 0.9333333373069763, 0.9666666388511658, 0.9666666388511658, 0.8333333134651184, 0.9666666388511658, 1.0]


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x, encoded_y, test_size=0.2, random_state=9)
model = build_DNN()
fit_hist = model.fit(X_train, Y_train, batch_size=5, 
                    epochs=10, verbose=0)
print(fit_hist.history['accuracy'][-1])
print(model.evaluate(X_test, Y_test, verbose=0)[1])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


0.9583333134651184
1.0


In [ ]:
def build_DNN_hidden_num(hidden_params):
    model = Sequential()
    model.add(Dense(hidden_params[0], input_dim=4, activation='relu'))
    model.add(Dense(hidden_params[1], activation='relu'))
    model.add(Dense(hidden_params[2], activation='relu'))
    model.add(Dense(3, activation='softmax'))
    opt = Adam(lr=0.01)
    model.compile(opt, loss='categorical_crossentropy',
              metrics=['accuracy'])
    return model

In [ ]:
hidden_params = [[32, 64, 128], [128, 64, 32], [64, 26, 64]]
for param in hidden_params:
    model = build_DNN_hidden_num(param)
    fit_hist = model.fit(X_train, Y_train, batch_size=5, 
                    epochs=10, verbose=0)
    print(fit_hist.history['accuracy'][-1])
    print(model.evaluate(X_test, Y_test, verbose=0)[1])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


0.8500000238418579
0.8333333134651184
0.9666666388511658
1.0
0.9416666626930237
0.9333333373069763


In [ ]:
hidden_params = [[512, 256, 128], [256, 128, 64], [256, 64, 32]]
for param in hidden_params:
    model = build_DNN_hidden_num(param)
    fit_hist = model.fit(X_train, Y_train, batch_size=5, 
                    epochs=10, verbose=0)
    print(fit_hist.history['accuracy'][-1])
    print(model.evaluate(X_test, Y_test, verbose=0)[1])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


0.9583333134651184
1.0
0.8833333253860474
1.0
0.8500000238418579
0.9666666388511658


In [ ]:
hidden_params = [[1024, 64, 32], [512, 64, 32], [64, 64, 32]]
for param in hidden_params:
    model = build_DNN_hidden_num(param)
    fit_hist = model.fit(X_train, Y_train, batch_size=5, 
                    epochs=10, verbose=0)
    print(fit_hist.history['accuracy'][-1])
    print(model.evaluate(X_test, Y_test, verbose=0)[1])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


0.925000011920929
0.9333333373069763
0.9166666865348816
1.0
0.9583333134651184
1.0


In [ ]:
models = []
for i in range(10):
    model = build_DNN_hidden_num([128, 64, 32])
    model.fit(X_train, Y_train, batch_size=5, 
                    epochs=10, verbose=0)
    models.append(model)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
preds = []
for model in models:
    pred = model.predict(X_test)
    preds.append(pred)


In [ ]:
preds = np.array(preds)
print(preds.shape)

(10, 30, 3)


In [ ]:
pred_value = []
for j in range(len(X_test)):
  pred_result = []
  for i in range(10):
    pred_result.append(np.argmax(preds[i][j]))
  result = Counter(pred_result)
  print(result)
  max_value = 0
  for key in result.keys():
    if max_value < result[key]:
      max_value = result[key]
      max_key = key
  pred_value.append(max_key)
print(pred_value)

Counter({2: 10})
Counter({1: 7, 2: 3})
Counter({2: 10})
Counter({2: 10})
Counter({1: 9, 2: 1})
Counter({0: 10})
Counter({0: 10})
Counter({0: 10})
Counter({1: 9, 2: 1})
Counter({0: 10})
Counter({0: 10})
Counter({1: 8, 2: 2})
Counter({1: 8, 0: 2})
Counter({1: 9, 2: 1})
Counter({0: 10})
Counter({1: 9, 0: 1})
Counter({0: 10})
Counter({1: 7, 2: 3})
Counter({2: 10})
Counter({0: 10})
Counter({0: 10})
Counter({0: 10})
Counter({2: 10})
Counter({0: 10})
Counter({2: 10})
Counter({1: 9, 2: 1})
Counter({0: 10})
Counter({2: 10})
Counter({0: 10})
Counter({2: 10})
[2, 1, 2, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0, 2, 0, 2, 1, 0, 2, 0, 2]


In [ ]:
from collections import Counter
result = Counter(pred_result)
print(result)
max_value = 0
for key in result.keys():
  if max_value < result[key]:
    max_value = result[key]
    max_key = key
print(max_key)

Counter({1: 7, 2: 3})
1


In [ ]:
my_sample = np.random.randint(30)
sample = X_test[my_sample]
print(sample)
sample = sample.reshape(-1, 4)
print(sample)
pred = model.predict(sample)
print('pred is :', pred)
print('actual is :', Y_test[my_sample])
print('Target :', 
      iris.target_names[np.argmax(Y_test[my_sample])])
print('Prediction after learning is :', 
      iris.target_names[np.argmax(pred)])

[4.6 3.2 1.4 0.2]
[[4.6 3.2 1.4 0.2]]
pred is : [[9.9999988e-01 9.4420585e-08 5.7959525e-08]]
actual is : [1. 0. 0.]
Target : setosa
Prediction after learning is : setosa
